# This is a basic workflow to help you get started with Actions

name: Backup latest articles

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths-ignore: "./backup"
  schedule:
    - cron: 0 * * * *

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Ensure Directory
        run:  New-Item -ItemType Directory "backup" -Force

      # Runs a set of commands using the runners shell
      - name: Fetch wikitext
        working-directory: "./backup"
        run: |
          $data = @{action='query'; prop='revisions'; rvprop='content'; format='json'; titles='超異域公主連結|超異域公主連結/登場角色一覽'}
          $res = Invoke-RestMethod 'https://wiki.komica.org/api.php' -Body $data
          $res.query.pages.PSObject.Properties.Value | ForEach-Object {Set-Content -Path "$($_.title.replace('/','_')).wiki" -Value $_.revisions.'*'}

      - name: Push wikitext
        working-directory: "./backup"
        run: |
          git config --global user.name 'KiruyaMomochi'
          git config --global user.email 'KiruyaMomochi@users.noreply.github.com'
          $time = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Asia/Taipei').ToString("yyyy-MM-dd HH:mm:ss")
          git commit -m $time
          git push
